name: Deploy to Minikube using GitHub Actions

on: [push]
  
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build Node.js Docker Image and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Build image
      run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build --no-cache -f ./Dockerfile -t devopshint/node-app:latest .
          echo -n "verifying images:"
          docker images         
    - name: Clean previous deployment
      run: |
          kubectl delete deployment nodejs-app || true
          kubectl delete service nodejs-app || true
    - name: Deploy to minikube
      run:
        kubectl apply -f k8s-node-app.yaml
    - name: Inspect server.js inside pod
      run: |
          echo "=== Contenido de server.js dentro del contenedor ==="
          kubectl exec $(kubectl get pod -l app=nodejs-app -o jsonpath="{.items[0].metadata.name}") -- cat /usr/src/app/server.js
    - name: Test service URLs
      run: |
          minikube service list
          minikube service nodejs-app --url
